### ISSUE TITLE
Navigating within a service using the INavigator adds an extra '/_/'

### ISSUE THREAD

**Issue by pavsaund** [dolittle-entropy/vanir#171] opened 2021-04-09 10:48 UTC
When navigating using the `INavigator` from within a microservice an extra `/_/` is appended to the url. This also happens when ex: clicking the back-button.

Adding some more information. The local router is set up to navigate with the underscore, and this works when ex: clicking links. in the DOM.

I don't think this is new behaviour, but in implementing local functionality to refresh the a component on navigation (#170) I think we discovered this.

**Comment by pavsaund** [comment] 2021-04-09 11:38
Additional information: I think this is the reason the extra `/_/` is added: https://github.com/dolittle-entropy/vanir/blob/d7ef1cde37c2676f0c17f5aacd5e344338c0f6db/Source/react/routing/RoutingViewModel.tsx

**Comment by einari** [comment] 2021-04-11 06:23
The additional `/_/` prefix added is actually as expected, it also adds the name of microservice there. The reason for this is that in the composition the public endpoint is in fact `/_/<microservice name>/<your routes/`. The use of `MicroserviceRoute` then also appends this information. But I think there is a gap here somewhere, I'm investigating what that is and also thinking if this can be done in a better - hopefully less intrusive way.

For reference: https://github.com/dolittle-entropy/vanir/blob/d7ef1cde37c2676f0c17f5aacd5e344338c0f6db/Source/react/routing/MicroserviceRoute.tsx

**Comment by einari** [comment] 2021-04-11 08:47
I'm going to close this issue, as I think it is by design. What I have done however, is add documentation for how it is intended to work and be used: https://github.com/dolittle-entropy/vanir/blob/main/Documentation/frontend/react/routing.md

**Closed by einari** 2021-04-11 08:47 UTC
